workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        environment:
          unity: 2023.1.10f1
        artifacts:
            - &zip Assets/*
            - *md
        scripts:
            - name: Step 1
              script: | 
                echo 'Hello World!'
    sample-workflow1212:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        scripts:
            - name: Step 1
              script: | 
                echo 'Hello World?'
